config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  # get 'sessions/new'
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get 'signup' => "user#new"
  get 'checkins/new' => "checkin#new"
  post 'checkins/new' => "checkin#create"
  post 'signup' => "user#create"
  get 'users/show' => "user#show"
  get 'users/edit' => "user#edit"
  post 'users/edit' => "user#update"

  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :user
end

app/models/gym.rb
class Gym < ApplicationRecord
    has_many :users
end

app/models/paycycle.rb
class Paycycle < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :gym

    has_many :checkins

    validates :email,
    presence: true,
    uniqueness: {case_sensitive: false}

    validates :password, 
    length: { in: 6..36 }, 
    on: :create

    has_secure_password

    def self.authenticate(params)
        User.find_by_email(params[:email]).try(:authenticate, params[:password])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_user

  def is_authenticated
    unless current_user
      flash[:danger] = "Credentials Invalid"
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/checkin_controller.rb
class CheckinController < ApplicationController
  def new
    @checkin = Checkin.new
  end

  def create
    checkin_params[:user_id] = @current_user.id
    render json: Checkin.create(checkin_params)
    # redirect_to "/users/show"
  end

  private

  def checkin_params
    params.require(:checkin).permit(:start_time, :end_time, :user_id)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.authenticate(user_params)
    if user
      session[:user_id] = user.id
      flash[:success] = "User logged in!!"
      redirect_to "/users/show"
    else
      flash[:danger] = "Credentials Invalid!!"
      redirect_to login_path
    end
  end


  def destroy
    session[:user_id] = nil
    flash[:success] = "User logged out!!"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController


  COMMON_YEAR_DAYS_IN_MONTH = [nil, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

  def days_in_month(month, year = Time.now.year)
     return 29 if month == 2 && Date.gregorian_leap?(year)
     COMMON_YEAR_DAYS_IN_MONTH[month]
  end

  def days_left_in_month(month)
    current_date = Time.new
    date = current_date.day
    return days_in_month(month) - date + 1
  end


  def create
    # render json: User.create(user_params)
    User.create(user_params)
    redirect_to login_path
  end

  def new
    @user = User.new
    @gyms = Gym.all
  end

  def show
    @user = @current_user
    if @current_user.paycycle > 0
      @paycycle = Paycycle.find(@current_user.paycycle)
    end
    @checkins = Checkin.where(:user_id => @current_user.id)
    gon.num_checkins = @checkins.length
    gon.max_checkins = days_in_month(4)
    gon.days_left = days_left_in_month(4)
    gon.user_id = @current_user.id
  end

  def edit
    @user = @current_user
    @paycycles = Paycycle.all
    @gyms = Gym.all
  end

  def update
    u = User.find(@current_user.id)
    u.update(user_params)
    redirect_to "/users/show"
  end

  def wentToGymBeezies
    puts "Hey thare yall gym brethren"
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :name, :paycycle, :gym_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkin_helper.rb
module CheckinHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/checkin/new.html.erb
<div class="text-center">
  <h1>So you want to go to the gym?</h1>

  <div class="container text-left">
    <%= bootstrap_form_for :checkin do |p| %>
      <%= p.datetime_field :start_time, placeholder: "Enter time u want to work out"  %>
      <%= p.datetime_field :end_time, placeholder: "Enter time u 'finished' working out"  %>
      <%= p.primary "Submit" %>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= typekit 'oyb2kyi' %>
    <title>AuthBoiler</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Palanquin+Dark:500' rel='stylesheet'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/navbar" %>

    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1 class="col-xs-6 col-xs-offset-3" id="home_page_title"><span class="orange">Get paid</span> to work out and <span class="orange">save</span> on
your gym membership</h1>

<div class="row" id="home_icon_row">
  <div class="col-xs-12 col-md-2 col-md-offset-3">
    <%= image_tag 'SignUpIcon.svg', id: 'home_svg' %>
    <br>
    <h3>1. Sign Up</h3>

    <h5>Find your gym and sign up through whealth.</h5>
  </div>
  <div class="col-xs-12 col-md-2 col-md-offset-0">
    <%= image_tag 'Stretchicon.svg', id: 'home_svg' %>
    <br>
    <h3>2. Work Out</h3>

    <h5>Every time you go to the gym, you earn a $1 rebate on your membership.</h5>
  </div>
  <div class="col-xs-12 col-md-2 col-md-offset-0">
    <%= image_tag 'RecieveCoins.svg', id: 'home_svg' %>
    <br>
    <h3>3. Get Paid</h3>

    <h5>At the end of the month, you can get the money you have earned back as cash, or have it automatically applied to next month.</h5>
  </div>

</div>
<br>
<br>
<br>
<div class="row">
  <h2 class="text-center">So how does it work?</h2>
  <br>
  <div class="col-xs-6 col-xs-offset-3">
    Whealth works with local gyms to give you a way to save money on your gym membership. It's simple - the more you go, the less you pay.
  <br>
  <br>
    You find your gym on Whealth, sign up, and agree to a montly rate (varies gym to gym).
  <br>
  <br>
    Every day you go, you earn $1. At the end of the month you can choose to have the money you earned put towards your next bill, or sent to your bank account.
  </div>
  <br>
</div>
  <button id="sign_up"><a href="/signup">Sign Up!</a></button>

app/views/partials/_flash.html.erb
<%- flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
        <%= value %>
    </div>
<%end%>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="navbar-header">
    <a id="white-brand" class="navbar-brand" href="/"><%= image_tag 'whealth.png', id: "nav_logo" %></a>
  </div>
  <ul id="white" class="nav navbar-nav pull-right">
    <% if @current_user %>
      <li><a class="btn default-btn" id="default-btn" href="/users/show">Hello, <%= @current_user.name%></a></li>
      <li><%= link_to "Edit Profile", users_edit_path(@current_user), class: 'btn default-btn', id: 'default-btn'%></li>
      <li><a class="btn default-btn" id="default-btn" href="/logout">Logout</a></li>
    <% else %>
      <li><a class="btn default-btn" id="default-btn" href="/login">Login</a></li>
      <li><a class="btn default-btn" id="default-btn" href="/signup">Signup</a></li>
    <% end %>
  </ul>
</div>

app/views/user/edit.html.erb
<div class="text-center">
  <h1>Edit My Gym Info</h1>
  <div class="container text-left">
    <%= bootstrap_form_for :user do |p| %>
      <%= p.collection_select :paycycle, @paycycles, :id, :name %>
      <%= p.collection_select :gym_id, @gyms, :id, :name %>
      <%= p.primary "Submit", class: 'btn default-btn' %>
      <a href="/users/show" class="btn default-btn">Go back</a> 
    <% end %>
  </div>
</div>

app/views/user/new.html.erb
<div class="col-xs-8 col-xs-offset-2 text-left">
<h1>Signup</h1>
  <%= bootstrap_form_for :user do |p| %>
    <%= p.text_field :name, placeholder: "Enter your name"  %>
    <%= p.email_field :email, placeholder: "Enter your email"  %>
    <%= p.password_field :password, placeholder: "Enter your password"  %>
    <%= p.collection_select :gym_id, @gyms, :id, :name %>
    <%= p.primary "Submit", class: 'btn default-btn' %>
  <% end %>
</div>

app/views/user/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="row">
        <div class="col-xs-6">
          <h2>Total earned this <br>month:</h2>
        </div>
        <div class="col-xs-6">
          <h1 class="text-right">$<strong><%= @checkins.length %></strong></h1>
        </div>
      </div>
        <hr>
      <h4>At the end of this month, please: </h4>
      <br>
      <button id="selected" class="btn btn-profile">Deposit it into my bank account</button>
      <br><br>
      <button class="btn btn-profile">Put it towards my next membership fee</button>
    </div>
    <div class="col-xs-12 col-sm-6 graphs">
      <div id="chart"></div>
      <div class="btn-group right">
          <button type="button" id="pieTrue" class="btn btn-primary toggle"><i class="fa fa-pie-chart" aria-hidden="true"></i></button>
          <button type="button" id="pieFalse" class="btn btn-primary toggle"><i class="fa fa-tasks" aria-hidden="true"></i></button>
      </div>

    </div>
  </div>



<div class="row">
  <div class="col-xs-12 col-sm-6 graphs">
    <h2 class="text-left">Total earned to date: <span class="move-right">$<strong><%= @current_user.dividend %></strong></span></h2>
    <hr>
      <h3 id="month">April</h3>
      <div id="line">
      </div>
      <div id="calendar">
        <%= month_calendar events: @checkins do |date, checkins| %>
            <%= date %>

            <% checkins.each do |checkin| %>
                <div>
                    <%= @current_user.gym.name %>
                </div>
            <% end %>
        <% end %>
      </div>
      <div class="btn-group">
        <button type="button" id="lineTrue" class="btn btn-primary toggle"><i class="fa fa-line-chart" aria-hidden="true"></i></button>
        <button type="button" id="lineFalse" class="btn btn-primary toggle"><i class="fa fa-calendar" aria-hidden="true"></i></button>
      </div>
  </div>
  <div class="col-xs-12 col-sm-offset-1 col-sm-5">
    <br><br>
    <h2><strong><%= @checkins.length %></strong> <small class="white">days you've gone this week</small></h2>
    <hr>
    <br><br>
    <% if @current_user.id == 1 %>
      <h2><strong>29%</strong> <small class="white">increase from last week</small></h2>
      <hr>
      <br><br>
      <h2><strong>30%</strong> <small class="white">increase from last month</small></h2>
      <hr>
    <% else %>
      <h2><strong>0%</strong> <small class="white">increase from last week</small></h2>
      <hr>
      <br><br>
      <h2><strong>0%</strong> <small class="white">increase from last month</small></h2>
      <hr>
    <% end %>

  </div>
</div>


</div>


<script>
   var pie = true;
   var line = true;
   var isGoal = false;
   var chart, chart2;
   var numCheckins = gon.num_checkins;
   var maxCheckins = gon.max_checkins;
   var daysLeft = gon.days_left;
   var lineData = []
   if(gon.user_id === 1){
     lineData = ['April', 1, 4, 5, 0];
   } else {
     lineData = ['April', 1, 0, 0, 0];
   }

renderChart();
$("#pieTrue").css("background-color", "#FFA24F ")
$("#pieFalse").css("background-color", "#205A66 ")
function changeBorderPie() {
    if (!pie) {
        $("#pieTrue").css("background-color", "#205A66 ")
        $("#pieFalse").css("background-color", "#FFA24F ")
    } else {
        $("#pieTrue").css("background-color", "#FFA24F ")
        $("#pieFalse").css("background-color", "#205A66 ")
    }
}

$("#lineTrue").css("background-color", "#FFA24F ")
$("#lineFalse").css("background-color", "#205A66 ")
function changeBorderLine() {
    if (line) {
        $("#lineTrue").css("background-color", "#FFA24F ")
        $("#lineFalse").css("background-color", "#205A66 ")
    } else {
        $("#lineTrue").css("background-color", "#205A66 ")
        $("#lineFalse").css("background-color", "#FFA24F ")
    }
}

$("#lineTrue").click(function() {
    line = true
    renderChart();
    changeBorderLine();
});

$("#lineFalse").click(function() {
    line = false
    renderChart();
    changeBorderLine();
});

$("#pieTrue").click(function() {
  console.log("pie true is clicked")
    pie = true
    renderChart();
    changeBorderPie();
});

$("#pieFalse").click(function() {
  console.log("pie false is clicked")
    pie = false
    renderChart();
    changeBorderPie();
});

function renderChart() {
    if(pie){
        var chart = c3.generate({
            bindto: '#chart',
            data: {
            columns: [
                ["days you've been to the gym this month", numCheckins],
                ['days total this month', daysLeft],
            ],
            type: 'pie'
            },
            pie: {
                label: {
                  format: function (value, ratio, id) {
                    if(value === numCheckins){
                        return d3.format('')(value);
                    }
                    else if (value === daysLeft){
                        return;
                    }
                  }
                }
            }
        });
    } else {
        var chart2 = c3.generate({
            bindto: '#chart',
            data: {
                columns: [
                    ['Dollars Saved', (numCheckins)],
                ],
                type: 'gauge',
            },
            color: {
                pattern: ['#FFA24F', '#FFA24F', '#205A66', '#205A66'], // the three color levels for the percentage values.
                threshold: {
                    values: [30, 60, 90, 100]
                }
            },
            size: {
                height: 180
            },
            gauge: {
                max: maxCheckins,
                label: {
                    format: function(val, ratio){
                        return '$' + val;
                    }
                }
            },
        });
    }
    if (line){
        $("#line").show()
        var chart = c3.generate({
            bindto: '#line',
            data: {
                columns: [
                    lineData
                    // ['April', 1, 4, 5, 0],
                ],
            },
            axis: {
                x: {
                    label: 'Weeks'
                },
                y: {
                    label: 'Gym Visits'
                }
            }
        });
        $('#calendar').hide()
    } else {
        $("#line").hide()
        $('#calendar').show()
    }


}

</script>